### ISSUE TITLE
exploit available on exploit-db

### ISSUE THREAD

**Issue by LucaLuke13** [kesar/HTMLawed#27]
hello, 
I just noticed that there is an exploit for your project on exploit-db.com:
https://www.exploit-db.com/exploits/52023
Its not for the last ersion as far as I see but I wanted to inform you about this

**Comment by KorvinSzanto** [comment]
Looks like you're correct that the vulnerability is supposedly for previous releases and not the current release from February 2022.

This project is a mirror of https://bioinformatics.org/phplabware/internal_utilities/htmLawed/ and is pretty far out of date at this point. I'll see if I can take some time to get the newer versions tagged so that we're not so far out of date.
